# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 60)
        Form.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("QWidget{\n"
"    background-color:rgb(62, 62, 62);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.download = QtWidgets.QToolButton(Form)
        self.download.setStyleSheet("QToolButton{\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(0, 221, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download.setIcon(icon)
        self.download.setIconSize(QtCore.QSize(30, 30))
        self.download.setAutoRaise(True)
        self.download.setObjectName("download")
        self.gridLayout_2.addWidget(self.download, 0, 2, 1, 1)
        self.icon = QtWidgets.QLabel(Form)
        self.icon.setMinimumSize(QtCore.QSize(40, 40))
        self.icon.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.icon.setFont(font)
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("icons/G.png"))
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.gridLayout_2.addWidget(self.icon, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Solicitud = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Solicitud.setFont(font)
        self.Solicitud.setObjectName("Solicitud")
        self.gridLayout.addWidget(self.Solicitud, 0, 0, 1, 1)
        self.info = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.download.setToolTip(_translate("Form", "Descargar contenido"))
        self.download.setText(_translate("Form", "..."))
        self.Solicitud.setText(_translate("Form", "https://www.yoogle.com/widget"))
        self.info.setText(_translate("Form", "https://www.yoogle.com/widget"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
